
import { Branch, Material } from './types';

export const BRANCHES: Branch[] = [
  { id: '1', name: 'HQ Warehouse', city: 'Johannesburg', lat: -26.2041, lng: 28.0473, address: '12 Industrial Way, Isando', phone: '+27 11 555 0100', mainHubImage: '' },
  { id: '2', name: 'Coastal Hub', city: 'Cape Town', lat: -33.9249, lng: 18.4241, address: '45 Harbour Road, Paarden Eiland', phone: '+27 21 555 0200', mainHubImage: '' },
  { id: '3', name: 'East Port', city: 'Durban', lat: -29.8587, lng: 31.0218, address: '88 Logistics Drive, Pinetown', phone: '+27 31 555 0300', mainHubImage: '' },
  { id: '4', name: 'Central Distribution', city: 'Bloemfontein', lat: -29.0852, lng: 26.1596, address: '15 Highview Ave, Hamilton', phone: '+27 51 555 0400', mainHubImage: '' },
];

export const MATERIALS: Material[] = [
  // HARDWARE - PRINTERS
  { 
    id: 'hdw-rol-vg3-640',
    sku: 'RD-VG3-640',
    name: 'Roland TrueVIS VG3-640',
    department: 'Hardware',
    category: 'Eco-Solvent Printer/Cutter',
    brand: 'Roland DG',
    brandId: 'b-roland',
    range: 'TrueVIS',
    rangeId: 'r-truevis',
    series: 'VG3 Series',
    seriesId: 's-vg3',
    modelNumber: 'VG3-640',
    density: 0,
    tempRange: '15 to 32°C', 
    description: 'The TrueVIS VG3-640 is the ultimate professional solution for signage, featuring integrated print and contour cut capabilities. Powered by the TR2 ink system including Orange and Green, it offers an expanded color gamut and superior image quality.',
    features: ['8-Color Ink Configuration (CMYKLcLmOrGr)', 'Integrated Piezo Variable Inkjet', 'Bluetooth-enabled Roland DG Mobile Panel', 'Automated Media Gap & Feed Compensation'],
    applications: ['Vehicle Wraps', 'Backlit Displays', 'Die-Cut Decals', 'Exhibition Graphics', 'Banners'],
    standardSizes: ['1625mm (64")'],
    variants: [{ type: 'model', value: 'VG3-640 Standard' }],
    media: [{ url: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&q=80&w=1200', type: 'image' }],
    pros: ['Industry-leading color accuracy', 'Efficient dual-mode cutting', 'Reliable unattended production'],
    cons: ['Significant floor space requirement', 'Strict environmental temperature control'],
    price: 315000,
    pricingType: 'unit',
    technicalSpecs: [
      { label: 'Max Print Speed', value: '21.0 m²/h (Standard)' },
      { label: 'Resolution', value: 'Max 1200 dpi' },
      { label: 'Ink Type', value: 'TR2 Eco-Solvent' },
      { label: 'Cutting Force', value: 'Up to 500gf' }
    ],
    tags: ['Roland', 'Printing', 'Cutting', 'Hardware'],
    documents: []
  },
  { 
    id: 'hdw-mim-ucjv300-160',
    sku: 'MK-UCJV300-160',
    name: 'Mimaki UCJV300-160',
    department: 'Hardware',
    category: 'UV-LED Printer/Cutter',
    brand: 'Mimaki',
    brandId: 'b-mimaki',
    range: 'UCJV Series',
    rangeId: 'r-ucjv',
    series: 'UCJV300',
    seriesId: 's-ucjv300',
    modelNumber: 'UCJV300-160',
    density: 0,
    tempRange: '20 to 30°C', 
    description: 'A versatile UV-LED inkjet printer/cutter that enables 4-layer printing for backlit graphics. It features instant-dry LUS-170 inks that allow for immediate finishing and lamination, significantly reducing turnaround times.',
    features: ['4-Layer Printing (Day/Night View)', 'LUS-170 GREENGUARD Gold Inks', 'ID Cut Function for automated cutting', 'White & Clear Ink Support'],
    applications: ['Backlit Displays', 'Window Graphics', 'Floor Decals', 'Packaging Prototypes'],
    standardSizes: ['1610mm'],
    variants: [],
    media: [{ url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=1200', type: 'image' }],
    pros: ['Instant curing for fast delivery', 'Unique multi-layer effects', 'Low heat emission for thin media'],
    cons: ['UV inks have limited stretch compared to cast vinyl inks'],
    price: 345000,
    pricingType: 'unit',
    technicalSpecs: [
      { label: 'Max Resolution', value: '1200 dpi' },
      { label: 'Curing Unit', value: 'UV-LED' },
      { label: 'Ink Type', value: 'LUS-170 / LUS-200' },
      { label: 'Max Media Thickness', value: '1.0mm' }
    ],
    tags: ['Mimaki', 'UV-LED', 'Backlit', 'Hardware'],
    documents: []
  },
  { 
    id: 'hdw-3dp-raise3d-pro3',
    sku: 'R3D-PRO3-PLUS',
    name: 'Raise3D Pro3 Plus',
    department: 'Hardware',
    category: '3D Printer',
    brand: 'Raise3D',
    brandId: 'b-raise3d',
    range: 'Pro Series',
    rangeId: 'r-proseries',
    modelNumber: 'Pro3 Plus',
    density: 0,
    tempRange: '15 to 30°C', 
    description: 'A professional-grade large-format 3D printer featuring a dual-extruder system and an independent modular system. Designed for continuous production and rapid prototyping with high reliability and precision.',
    features: ['Dual Extruder System', 'Interchangeable Hotends', 'Air Flow Manager with HEPA filter', 'EVE Smart Assistant'],
    applications: ['Jigs and Fixtures', 'Functional Prototypes', 'Low Volume Production', 'Educational Models'],
    standardSizes: ['300 x 300 x 605 mm'],
    variants: [],
    media: [{ url: 'https://images.unsplash.com/photo-1631282121775-58532420a324?auto=format&fit=crop&q=80&w=1200', type: 'image' }],
    pros: ['Massive build volume', 'Highly consistent layer adhesion', 'Remote production management'],
    cons: ['Slow build speeds for large volume prints'],
    price: 115000,
    pricingType: 'unit',
    technicalSpecs: [
      { label: 'Layer Height', value: '0.01 - 0.25mm' },
      { label: 'Max Nozzle Temp', value: '300°C' },
      { label: 'Build Plate Temp', value: 'Max 120°C' },
      { label: 'Filament Diameter', value: '1.75mm' }
    ],
    tags: ['3D Printing', 'Industrial', 'Raise3D', 'Prototyping'],
    documents: []
  },

  // VINYLS & MEDIA
  {
    id: 'vnl-ora-651-gloss',
    sku: 'OR-651-G',
    name: 'Oracal 651 Intermediate Vinyl',
    department: 'Signage Materials',
    category: 'Vinyl',
    brand: 'Oracal',
    brandId: 'b-oracal',
    range: '651 Series',
    rangeId: 'r-651',
    series: '651 Gloss',
    seriesId: 's-651gloss',
    density: 0,
    tempRange: '-40 to +80°C',
    description: 'ORACAL 651 is the industry standard for intermediate calendered vinyl. It features a 2.5 mil thickness and a 5-year outdoor durability, making it perfect for general signage, decals, and flat-surface vehicle lettering.',
    features: ['70 Micron (2.5 mil)', 'Solvent Polyacrylate Permanent Adhesive', '60+ Vibrant Gloss Colors', 'Clear, water-based adhesive'],
    applications: ['POB Signage', 'Flat Surface Decals', 'Retail Window Graphics', 'Exhibition Displays'],
    standardSizes: ['1260mm x 50m', '630mm x 50m'],
    variants: [
      { type: 'color', value: 'Gloss White' },
      { type: 'color', value: 'Gloss Black' },
      { type: 'color', value: 'Transparent' }
    ],
    media: [{ url: 'https://images.unsplash.com/photo-1626608322397-f4e507d10c73?auto=format&fit=crop&q=80&w=1200', type: 'image' }],
    pros: ['Excellent weeding properties', 'Cost-effective for bulk signage', 'High dimensional stability'],
    cons: ['Not suitable for deep recesses or corrugations'],
    price: 185,
    pricingType: 'meter',
    fullRollLength: 50,
    technicalSpecs: [
      { label: 'Thickness', value: '70 micron' },
      { label: 'Outdoor Durability', value: '5 Years' },
      { label: 'Adhesive Power', value: '18 N/25 mm' },
      { label: 'Tensile Strength', value: '19 MPa' }
    ],
    tags: ['Oracal', 'Vinyl', 'Signage', 'Intermediate'],
    documents: []
  },
  {
    id: 'vnl-ora-751-gloss',
    sku: 'OR-751-HP',
    name: 'Oracal 751 High Performance Cast',
    department: 'Signage Materials',
    category: 'Vinyl',
    brand: 'Oracal',
    brandId: 'b-oracal',
    range: '751 Series',
    rangeId: 'r-751',
    series: '751 Gloss',
    seriesId: 's-751gloss',
    density: 0,
    tempRange: '-50 to +110°C',
    description: 'A high-performance cast vinyl designed for high-quality vehicle lettering and long-term signage. It offers excellent conformability over simple curves and rivets with an 8-year outdoor life.',
    features: ['60 Micron (2.4 mil)', 'Cast PVC Film', 'Exceptional conformability', 'Dimensional stability'],
    applications: ['High-Quality Vehicle Lettering', 'Marine Graphics', 'Long-term Signage', 'Transportation Graphics'],
    standardSizes: ['1260mm x 50m'],
    variants: [],
    media: [{ url: 'https://images.unsplash.com/photo-1626608322397-f4e507d10c73?auto=format&fit=crop&q=80&w=1200', type: 'image' }],
    pros: ['Extended outdoor life', 'Thin profile for "painted-on" look', 'Superior weather resistance'],
    cons: ['Higher cost than calendered vinyl'],
    price: 325,
    pricingType: 'meter',
    fullRollLength: 50,
    technicalSpecs: [
      { label: 'Thickness', value: '60 micron' },
      { label: 'Outdoor Durability', value: '8 Years' },
      { label: 'Elongation', value: 'min 150%' }
    ],
    tags: ['Oracal', 'Vinyl', 'Cast', 'High Performance'],
    documents: []
  },
  {
    id: 'vnl-ave-1105',
    sku: 'AD-MPI-1105-EA',
    name: 'Avery MPI 1105 Easy Apply RS',
    department: 'Signage Materials',
    category: 'Print Media',
    brand: 'Avery Dennison',
    brandId: 'b-avery',
    range: 'MPI 1100 Series',
    rangeId: 'r-mpi1100',
    series: 'MPI 1105 Series',
    seriesId: 's-mpi1105',
    density: 0,
    tempRange: '-45 to +82°C',
    description: 'The premier solution for vehicle wraps and demanding surfaces. Features Easy Apply RS technology for repositionability and slideability, and ultimate conformability around deep recesses and rivets.',
    features: ['50 Micron High Gloss Cast Film', 'Easy Apply RS (Repositionable/Slideable)', 'Long-term Removability', '10 Year Durability (Unprinted)'],
    applications: ['Full Vehicle Wraps', 'Fleet Graphics', 'Corrugated Surfaces', 'Architectural Decoration'],
    standardSizes: ['1370mm x 50m', '1524mm x 50m'],
    variants: [],
    media: [{ url: 'https://images.unsplash.com/photo-1614332287897-cdc485fa562d?auto=format&fit=crop&q=80&w=1200', type: 'image' }],
    pros: ['Unmatched application speed', 'Air egress for bubble-free finish', 'Excellent print resolution'],
    cons: ['Requires professional installation training'],
    price: 495,
    pricingType: 'meter',
    fullRollLength: 50,
    technicalSpecs: [
      { label: 'Thickness', value: '50 micron' },
      { label: 'Adhesive', value: 'Solvent Acrylic' },
      { label: 'Durability', value: '10 Years' },
      { label: 'Finish', value: 'Super Gloss' }
    ],
    tags: ['Avery', 'Wrap', 'Digital Print', 'Easy Apply'],
    documents: []
  },

  // RIGID SUBSTRATES
  { 
    id: 'eng-lx-pc-3mm',
    sku: 'IP-LX-PC-3MM',
    name: 'Lexan 9034 Polycarbonate (3mm)', 
    department: 'Engineering Materials',
    category: 'Polycarbonate', 
    brand: 'Lexan',
    brandId: 'b-lexan',
    range: '9034 Series',
    rangeId: 'r-9034',
    series: 'Lexan PC',
    seriesId: 's-lxpc',
    density: 1.20, 
    tempRange: '-40 to +120°C', 
    description: 'LEXAN 9034 is the standard general-purpose polycarbonate sheet. It is virtually unbreakable and 250 times stronger than glass. It offers high impact resistance and optical clarity for industrial safety and security applications.',
    features: ['Impact Strength (250x Glass)', 'High Light Transmission (88%)', 'UL 94 V-2 Flammability Rating', 'Excellent Thermal Stability'],
    applications: ['Safety Guards', 'Machine Viewing Panels', 'Anti-Vandal Glazing', 'Industrial Skylights'],
    standardSizes: ['2440 x 1220mm', '3050 x 2030mm'],
    variants: [
      { type: 'thickness', value: '3mm', priceOverride: 2850 },
      { type: 'thickness', value: '5mm', priceOverride: 4500 }
    ],
    media: [{ url: 'https://images.unsplash.com/photo-1504148455328-497c5efdf13a?auto=format&fit=crop&q=80&w=1200', type: 'image' }],
    pros: ['Incredible toughness', 'Lightweight compared to glass', 'Easy to cold-curve'],
    cons: ['Prone to surface scratches without hard-coat'],
    price: 2850,
    pricingType: 'unit',
    engineeringSpecs: { length: 2440, width: 1220, thickness: 3, weight: 10.7 },
    technicalSpecs: [
      { label: 'Light Transmission', value: '88%' },
      { label: 'Impact Strength', value: '900 J/m' },
      { label: 'Tensile Strength', value: '62 MPa' }
    ],
    tags: ['Safety', 'Impact', 'Industrial', 'Lexan'],
    documents: []
  },
  { 
    id: 'eng-px-cl-5mm',
    sku: 'PX-AC-CAST-CL-5',
    name: 'Perspex Clear Cast Acrylic (5mm)', 
    department: 'Engineering Materials',
    category: 'Acrylic', 
    brand: 'Perspex',
    brandId: 'b-perspex',
    range: 'Cast Series',
    rangeId: 'r-pxcast',
    series: 'Perspex Cast',
    seriesId: 's-pxcast',
    density: 1.19, 
    tempRange: '-40 to +80°C', 
    description: 'Genuine PERSPEX cast acrylic sheet. Known for its exceptional quality, clarity, and consistency. This 5mm sheet provides 92% light transmission, higher than that of glass, with a surface finish that is naturally UV stable.',
    features: ['92% Light Transmission', 'Natural UV Resistance', '10 Year Weathering Guarantee', 'Excellent Chemical Resistance'],
    applications: ['Premium POS Displays', 'Skylights', 'Furniture Fabrication', 'Corporate Signage'],
    standardSizes: ['2440 x 1220mm', '3050 x 2030mm'],
    variants: [
      { type: 'thickness', value: '3mm', priceOverride: 1450 },
      { type: 'thickness', value: '5mm', priceOverride: 2400 }
    ],
    media: [{ url: 'https://images.unsplash.com/photo-1590483736622-39da8af75620?auto=format&fit=crop&q=80&w=1200', type: 'image' }],
    pros: ['Superior optical clarity', 'Easy to thermoform and glue', 'High surface hardness'],
    cons: ['More brittle than Polycarbonate'],
    price: 2400,
    pricingType: 'unit',
    engineeringSpecs: { length: 2440, width: 1220, thickness: 5, weight: 17.6 },
    technicalSpecs: [
        { label: 'Refractive Index', value: '1.49' },
        { label: 'Rockwell Hardness', value: 'M 102' },
        { label: 'Flexural Strength', value: '116 MPa' }
    ],
    tags: ['Acrylic', 'Perspex', 'Display', 'Clarity'],
    documents: []
  },
  { 
    id: 'eng-cd-white-06',
    sku: 'CD-STEEL-WHITE-06',
    name: 'Chromodeck Steel Sheet (0.6mm)', 
    department: 'Signage Materials',
    category: 'Metal', 
    brand: 'Chromodeck',
    brandId: 'b-chromodeck',
    range: 'Steel Series',
    rangeId: 'r-metal',
    density: 7.85, 
    tempRange: '-20 to +100°C', 
    description: 'Chromodeck is a high-quality pre-painted galvanized steel sheet. It is a staple in the signage industry for rigid outdoor boards. The white finish is UV-resistant and designed for direct application of vinyl graphics.',
    features: ['Pre-painted UV-stable white', 'Galvanized steel core', 'Rust resistant', 'Flat surface for vinyl adhesion'],
    applications: ['Outdoor Billboard Signage', 'Construction Site Boards', 'Property Signage', 'Industrial Safety Signs'],
    standardSizes: ['2450 x 1225mm'],
    variants: [],
    media: [{ url: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=1200', type: 'image' }],
    pros: ['Extremely rigid and flat', 'Weather resistant for outdoor use', 'Cost effective for large signs'],
    cons: ['Heavy to transport', 'Sharp edges require careful handling'],
    price: 1150,
    pricingType: 'unit',
    engineeringSpecs: { length: 2450, width: 1225, thickness: 0.6, weight: 14.1 },
    technicalSpecs: [
      { label: 'Base Material', value: 'Galvanized Steel' },
      { label: 'Coating', value: 'Silicone Polyester' },
      { label: 'Salt Spray Resistance', value: '500 Hours' }
    ],
    tags: ['Metal', 'Steel', 'Signage', 'Rigid'],
    documents: []
  }
];
